
import React, { useState, useRef, useCallback, useMemo } from 'react';

interface ShaderNode {
  id: string;
  type: 'input' | 'math' | 'color' | 'output' | 'texture' | 'time';
  label: string;
  position: { x: number; y: number };
  inputs: string[];
  outputs: string[];
  value?: any;
}

interface ShaderEdge {
  id: string;
  from: string;
  fromOutput: string;
  to: string;
  toInput: string;
}

interface ShaderGraphProps {
  onCompile: (glsl: string) => void;
  onApplyToObjects: (materialId: string) => void;
}

const NODE_TEMPLATES: Record<string, Omit<ShaderNode, 'id' | 'position'>> = {
  color: { type: 'color', label: 'Color', inputs: [], outputs: ['rgb'], value: '#00f2ff' },
  time: { type: 'time', label: 'Time', inputs: [], outputs: ['value'] },
  multiply: { type: 'math', label: 'Multiply', inputs: ['a', 'b'], outputs: ['result'] },
  add: { type: 'math', label: 'Add', inputs: ['a', 'b'], outputs: ['result'] },
  sin: { type: 'math', label: 'Sin', inputs: ['x'], outputs: ['result'] },
  output: { type: 'output', label: 'Fragment Output', inputs: ['color', 'alpha'], outputs: [] },
  texture: { type: 'texture', label: 'Texture Sample', inputs: ['uv'], outputs: ['rgb', 'a'] },
};

const ShaderGraph: React.FC<ShaderGraphProps> = ({ onCompile, onApplyToObjects }) => {
  const [nodes, setNodes] = useState<ShaderNode[]>([
    { id: 'n1', type: 'color', label: 'Base Color', position: { x: 50, y: 100 }, inputs: [], outputs: ['rgb'], value: '#00f2ff' },
    { id: 'n2', type: 'output', label: 'Fragment Output', position: { x: 400, y: 150 }, inputs: ['color', 'alpha'], outputs: [] },
  ]);
  const [edges, setEdges] = useState<ShaderEdge[]>([]);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [draggingNode, setDraggingNode] = useState<string | null>(null);
  const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 });
  const canvasRef = useRef<HTMLDivElement>(null);

  const handleMouseDown = (nodeId: string, e: React.MouseEvent) => {
    const node = nodes.find(n => n.id === nodeId);
    if (node) {
      setDraggingNode(nodeId);
      setDragOffset({ x: e.clientX - node.position.x, y: e.clientY - node.position.y });
      setSelectedNode(nodeId);
    }
  };

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    if (draggingNode) {
      setNodes(prev => prev.map(n =>
        n.id === draggingNode
          ? { ...n, position: { x: e.clientX - dragOffset.x, y: e.clientY - dragOffset.y } }
          : n
      ));
    }
  }, [draggingNode, dragOffset]);

  const handleMouseUp = () => {
    setDraggingNode(null);
  };

  const addNode = (type: string) => {
    const template = NODE_TEMPLATES[type];
    if (template) {
      const newNode: ShaderNode = {
        ...template,
        id: `n${Date.now()}`,
        position: { x: 200, y: 200 }
      };
      setNodes(prev => [...prev, newNode]);
    }
  };

  const compileToGLSL = () => {
    // Simplified GLSL generation
    const glsl = `
// Generated by Willow Shader Graph
precision mediump float;

uniform float u_time;
uniform vec3 u_baseColor;

void main() {
  vec3 color = u_baseColor;
  float pulse = sin(u_time * 2.0) * 0.5 + 0.5;
  gl_FragColor = vec4(color * pulse, 1.0);
}
    `.trim();
    onCompile(glsl);
  };

  return (
    <div className="h-full flex flex-col bg-[#050a15] overflow-hidden">
      {/* Toolbar */}
      <div className="h-14 bg-[#0a1222] border-b border-cyan-900/40 px-6 flex items-center justify-between shrink-0">
        <div className="flex items-center space-x-4">
          <span className="text-[10px] font-black uppercase tracking-widest text-cyan-400">Shader Graph</span>
          <div className="w-px h-6 bg-cyan-900/40"></div>
          <div className="flex space-x-2">
            {Object.keys(NODE_TEMPLATES).map(type => (
              <button
                key={type}
                onClick={() => addNode(type)}
                className="px-3 py-1.5 bg-cyan-950/40 border border-cyan-500/20 rounded-lg text-[9px] font-black uppercase text-cyan-400 hover:bg-cyan-600/20 transition-all"
              >
                + {type}
              </button>
            ))}
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <button
            onClick={compileToGLSL}
            className="px-6 py-2 bg-cyan-600 hover:bg-cyan-500 text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all shadow-lg shadow-cyan-500/30"
          >
            Compile GLSL
          </button>
          <button
            onClick={() => onApplyToObjects('default')}
            className="px-6 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
          >
            Apply to Scene
          </button>
        </div>
      </div>

      {/* Canvas */}
      <div
        ref={canvasRef}
        className="flex-1 relative overflow-hidden cursor-crosshair"
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        style={{
          backgroundImage: 'radial-gradient(circle, #0a1222 1px, transparent 1px)',
          backgroundSize: '20px 20px'
        }}
      >
        {/* Edges */}
        <svg className="absolute inset-0 pointer-events-none">
          {edges.map(edge => {
            const fromNode = nodes.find(n => n.id === edge.from);
            const toNode = nodes.find(n => n.id === edge.to);
            if (!fromNode || !toNode) return null;
            return (
              <path
                key={edge.id}
                d={`M ${fromNode.position.x + 150} ${fromNode.position.y + 40} C ${fromNode.position.x + 250} ${fromNode.position.y + 40}, ${toNode.position.x - 50} ${toNode.position.y + 40}, ${toNode.position.x} ${toNode.position.y + 40}`}
                stroke="#00f2ff"
                strokeWidth={2}
                fill="none"
                opacity={0.6}
              />
            );
          })}
        </svg>

        {/* Nodes */}
        {nodes.map(node => (
          <div
            key={node.id}
            onMouseDown={(e) => handleMouseDown(node.id, e)}
            className={`absolute w-40 bg-[#0a1222]/95 border rounded-2xl shadow-2xl backdrop-blur-xl cursor-move transition-all ${selectedNode === node.id ? 'border-cyan-500 shadow-[0_0_30px_rgba(0,242,255,0.3)]' : 'border-cyan-900/40'
              }`}
            style={{ left: node.position.x, top: node.position.y }}
          >
            <div className={`px-4 py-2 border-b border-cyan-900/40 rounded-t-2xl ${node.type === 'output' ? 'bg-emerald-600/20' : node.type === 'color' ? 'bg-purple-600/20' : 'bg-cyan-600/10'
              }`}>
              <span className="text-[9px] font-black uppercase text-cyan-50 tracking-widest">{node.label}</span>
            </div>
            <div className="p-3 space-y-2">
              {node.inputs.map(input => (
                <div key={input} className="flex items-center space-x-2">
                  <div className="w-2 h-2 rounded-full bg-amber-500 border border-amber-400"></div>
                  <span className="text-[8px] text-slate-400 uppercase font-black">{input}</span>
                </div>
              ))}
              {node.type === 'color' && (
                <input
                  type="color"
                  value={node.value || '#00f2ff'}
                  onChange={(e) => setNodes(prev => prev.map(n => n.id === node.id ? { ...n, value: e.target.value } : n))}
                  className="w-full h-8 rounded-lg cursor-pointer"
                />
              )}
              {node.outputs.map(output => (
                <div key={output} className="flex items-center justify-end space-x-2">
                  <span className="text-[8px] text-slate-400 uppercase font-black">{output}</span>
                  <div className="w-2 h-2 rounded-full bg-cyan-500 border border-cyan-400"></div>
                </div>
              ))}
            </div>
          </div>
        ))}

        {/* Empty state */}
        {nodes.length === 0 && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center opacity-30">
              <p className="text-[12px] font-black uppercase tracking-widest text-cyan-400">Add nodes to build your shader</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ShaderGraph;
